permissions:
  contents: read
name: Integration Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    services:
      vault:
        image: hashicorp/vault:latest
        env:
          VAULT_DEV_ROOT_TOKEN_ID: root
          VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
        ports:
          - 8200:8200
        options: --cap-add=IPC_LOCK
        
      openbao:
        image: quay.io/openbao/openbao:latest
        env:
          BAO_DEV_ROOT_TOKEN_ID: root
          BAO_DEV_LISTEN_ADDRESS: 0.0.0.0:8201
        ports:
          - 8201:8201
        options: --cap-add=IPC_LOCK

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Build
      run: make build
    
    - name: Wait for Vault
      run: |
        timeout 30 bash -c 'until curl -f http://localhost:8200/v1/sys/health; do sleep 1; done'
    
    - name: Wait for OpenBao
      run: |
        timeout 30 bash -c 'until curl -f http://localhost:8201/v1/sys/health; do sleep 1; done'
    
    - name: Run integration tests
      run: make test-integration
      env:
        SCEP2ACME_INTEGRATION_TESTS: 1
        VAULT_URL: http://localhost:8200
        VAULT_TOKEN: root
        OPENBAO_URL: http://localhost:8201
        OPENBAO_TOKEN: root